name = "bucketdrive-workers"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[triggers.crons]]
cron = "0 3 * * *"

[[d1_databases]]
binding = "DB"
database_name = "bucketdrive-db"
database_id = ""
migrations_dir = "../../packages/shared/src/db/migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "bucketdrive-files"

[vars]
APP_URL = "http://localhost:5173"
API_URL = "http://localhost:8787"
